# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'social' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for social
pod 'Firebase'


  target 'socialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'socialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
